### ISSUE TITLE
DCAT: Distribution - Correction of adms:changetype

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#45] opened 2018-03-14 14:23 UTC
Reason:
adms:changeType does not exist in ADMS vocabulary therefore cannot create a verifiable controlled vocabulary constraint.

**Comment by makxdekkers** [comment] 2018-03-27 14:30
We're looking into this.

**Comment by addragan** [comment] 2018-10-01 10:56
The issue can be closed as it was related to issue https://github.com/SEMICeu/dcat-ap_shacl/issues/5 that was also closed.

**Comment by jakubklimek** [comment] 2018-11-21 13:12
@addragan I vote to reopen the issue, as the issue is not resolved. The non existent vocabulary is still referenced from DCAT-AP v1.2, creating confusion. I suggest either removing it from DCAT-AP, creating a different vocabulary for it, or somehow add the vocabulary to ADMS.

**Comment by addragan** [comment] 2019-07-23 12:19
The issue was re-opened as the non existent vocabulary is still referenced from DCAT-AP v1.2, creating confusion. Proposal to either removing it from DCAT-AP, creating a different vocabulary for it, or adding the vocabulary to ADMS. Please vote your preferred option.

**Comment by NatasaSofou** [comment] 2019-09-13 12:04
Proposed resolution: the non-existent vocabulary will be removed from DCAT-AP 2.0.
The issue will be closed. It can be reopened in case of proposals for creating a different vocabulary for it or adding the vocabulary to ADMS.

**Comment by NatasaSofou** [comment] 2019-09-24 11:07
#86

**Closed** 2019-11-25 09:19 UTC
Labels: release:2.0.0-november2019
