### ISSUE TITLE
Use GitHub releases as intended

### ISSUE THREAD

**Issue by sandervd** [SEMICeu/DCAT-AP#56] opened 2019-02-28 08:47 UTC
Releases are now committed into a folder in the repository. However, since git is a version control system that has releases as a first class citizen, it would be more appropriate to use those instead.

**Comment by bertvannuffelen** [comment] 2019-04-19 14:40
I am not so sure if git releases are the way to go. 
The problem is that the git tagging/branching not necessarily correspond to the document status. E.g. if your name is misspelled as author, then this is an editorial correction, not a change in the "release" of the standard. According to a strict source control view this correction requires a minor release.

I'm currently involved setting up repositories for standardization documents in git. It turns out that we cannot come up with a fools proof approach solely applying the github source control semantics. We are forced to introduce an additional layer on top of it in order to get the desired way of working, to get the best of both worlds: a unique pinpointing of the published state to a commit, but also an end-user perspective which does not care if the color of the page has changed.

Given the size of this repo, I am quite fine with the current approach.

**Comment by sandervd** [comment] 2019-04-24 11:51
> According to a strict source control view this correction requires a minor release.

I would tend to disagree; If semantic versioning (3 versioning levels instead of two) were applied for a standard, changing the author name would be at the patch level, clearly indicating that a 'bug' has been fixed, and clearly indicating that the standard hasn't changed.
Semantic versioning would have another benefit in the case of data exchange:  two systems communicate with the same major version of a specification would by definition be compatible. 
The current versioning strategy isn't very clear: Is DCAT-AP 1.2 backwards compatible with DCAT-AP 1.1?
Do you thing the introduction of semantic versioning, like in software, would cover all cases?
https://semver.org/

**Comment by addragan** [comment] 2019-07-23 12:22
Proposed resolution: Proposal to use GitHub for versioning control without creating separate folders for each release.

**Comment by bertvannuffelen** [comment] 2019-11-15 01:51
best to align the process for all semic managed specifications. Will be part of a more global approach.

**Comment by sandervd** [comment] 2019-12-20 16:39
I wrote a small script that could be the start of this discussion: https://github.com/sandervd/DCAT-AP--refactor/blob/master/rewrite.sh

I pushed the result to this repo so that you can have a look without running the script: https://github.com/sandervd/DCAT-AP

**Closed** 2023-06-21 13:39 UTC
Labels: future-work
